# Managed by Vimmite. The local image is built by `ujust vimmite-dev build`.
[vimmite-dev]
image=localhost/vimmite-dev:44
pull=false
root=false
replace=false
start_now=true
entry=true
nvidia=false
additional_flags="--group-add keep-groups"
additional_flags="--env SSH_AUTH_SOCK"
init_hooks="/usr/local/share/vimmite-dev/bootstrap-root"
